[package]
name = "xcm_minimal_indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.38"
subxt = {version = "0.42.1", features=["jsonrpsee"]}
thiserror = "2.0.12"
tokio = { version = "1.45.0", features=["full"]}
